name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # <-- Tambahkan baris ini agar tombol Run manual muncul

jobs:
  build:
    runs-on: ubuntu-latest
    # ... (sisa kodenya tetap sama)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.5'
          channel: 'stable'
          cache: true

      - run: flutter pub get
      
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: cripcheck
          path: build/app/outputs/flutter-apk/cripcheck.apk
